services:
  db-CitySharing:
    image: postgres:15-alpine
    container_name: db_CitySharing
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: CitySharing
    ports:
      - "5432:5432"
    volumes:
      # Mappa la cartella locale con gli script SQL nella cartella di init di Postgres
      - ./init-db:/docker-entrypoint-initdb.d
      # Volume per persistere i dati anche se spegni il container
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      # Stringa di connessione che punta al servizio 'db'
      DB_CONN: "user=postgres password=password dbname=CitySharing host=db-CitySharing"
    stdin_open: true # Necessario per scanf/input interattivi
    tty: true # Necessario per vedere l'output formattato bene
    depends_on:
      - db-CitySharing

volumes:
  postgres_data:
